### ISSUE TITLE
Fix compatibility with Beamer

### ISSUE THREAD

**Issue by scottkosty** [ho-tex/soul#8]
Currently some soul functionality does not work well with the Beamer class. Workarounds are needed to get things working, such as: https://tex.stackexchange.com/questions/41683/why-is-it-that-coloring-in-soul-in-beamer-is-not-visible

Would it be possible to fix things in the soul package so that the workaround are not needed?

**Comment by u-fischer** [comment]
I have sent a new version to ctan that hopefully resolves this.

**Comment by scottkosty** [comment]
@u-fischer great, thank you!
